# The MIT License (MIT)
#
# Copyright © 2025 The pyTooling Authors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the “Software”), to deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit
# persons to whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
name: File-Is-Executable
description: Check if listed files are executable.
inputs:
  files:
    description: List of filenames.
    type: string

runs:
  using: composite
  steps:
    - name: 📋 Verify file permissions
      shell: bash
      run: |
        # 📋 Verify file permissions
        set +e

        ANSI_LIGHT_RED=$'\x1b[91m'
        ANSI_LIGHT_GREEN=$'\x1b[92m'
        ANSI_NOCOLOR=$'\x1b[0m'

        errors=0
        while IFS=$'\r\n' read -r file; do
          # skip empty or comment lines
          [[ "${file}" == "" || "${file:0:1}" == "#" ]] && continue

          printf "%s" "Checking '${file}' ... "
          if [[ -x "$file" ]]; then
            printf "%s\n" "${ANSI_LIGHT_GREEN}[PASSED]${ANSI_NOCOLOR}"
          else
            printf "%s\n" "${ANSI_LIGHT_RED}[NOT EXECUTABLE]${ANSI_NOCOLOR}"
            printf "::error title=%s::%s\n" "file-is-executable" "File '${file}' isn't executable."
            errors=$((errors + 1))
          fi
        done <<<'${{ inputs.files }}'

        printf "\n"
        if [[ $errors -ne 0 ]]; then
          printf "%s\n" "${ANSI_LIGHT_RED}Counted ${errors} errors.${ANSI_NOCOLOR}"
          exit 1
        else
          printf "%s\n" "${ANSI_LIGHT_GREEN}No errors found.${ANSI_NOCOLOR}"
        fi
